changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New
      labels:
        - feature
    - title: Changed
      labels:
        - enhancement
        - breaking change
    - title: Fixed
      labels:
        - bug
    - title: Docs and plugin
      labels:
        - docs
        - plugin
    - title: Under the hood
      labels:
        - chore
        - dependencies
    - title: Other
      labels:
        - "*"
