#!/bin/sh
# check-commit-trailers.sh [range]: fail when a commit in range names an AI
# tool as a co-author or says it was generated by one. CI runs it on the
# commits of a pull request; .githooks/commit-msg removes such lines before
# they are ever committed. The default range is what main does not have.
set -eu
range="${1:-origin/main..HEAD}"
patterns="$(dirname "$0")/ai-trailers.txt"
bad=0
for c in $(git rev-list "$range"); do
	if git log -1 --format=%B "$c" | grep -qiEf "$patterns"; then
		echo "$(git log -1 --format='%h %s' "$c"): names an AI tool as an author"
		git log -1 --format=%B "$c" | grep -iEf "$patterns" | sed 's/^/    /'
		bad=1
	fi
done
if [ "$bad" -ne 0 ]; then
	echo
	echo "Remove those lines (git rebase -i, reword) and push again."
	echo "To have them removed for you: git config core.hooksPath .githooks"
	exit 1
fi
echo "no AI co-author lines in $range"
